apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kafka
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "AKIA5KJY35NMPFYXEPDR"
  AWS_SECRET_ACCESS_KEY: "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"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: python
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "AKIA5KJY35NMPFYXEPDR"
  AWS_SECRET_ACCESS_KEY: "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"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: spark-operator
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "AKIA5KJY35NMPFYXEPDR"
  AWS_SECRET_ACCESS_KEY: "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"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: airflow
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "AKIA5KJY35NMPFYXEPDR"
  AWS_SECRET_ACCESS_KEY: "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"