apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kafka
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "***"
  AWS_SECRET_ACCESS_KEY: "***"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: python
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "***"
  AWS_SECRET_ACCESS_KEY: "***"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: spark-operator
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "***"
  AWS_SECRET_ACCESS_KEY: "***"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: airflow
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "***"
  AWS_SECRET_ACCESS_KEY: "***"
