apiVersion: v1
kind: Secret
metadata:
    name: kafka-secret
    namespace: airflow
type: Opaque
stringData:
    kafka-consumer-1: |
      {
        "conn_type": "kafka",
        "extra": {
        "bootstrap.servers": "my-cluster-kafka-bootstrap.kafka:9092",
        "group.id": "airflow1",
        "auto.offset.reset": "earliest"
        }
      }
    kafka-producer-1: |
      {
        "conn_type": "kafka",
        "extra": {
        "bootstrap.servers": "my-cluster-kafka-bootstrap.kafka:9092"
        }
      }
    aws-csn: |
      aws://AKIA5KJY35NMPFYXEPDR:Wq+ISE50gu/476N05vxKpxgTbrhEBNhR8Ca2MaX7
